### ISSUE TITLE
编译libimobiledevice生成so

### ISSUE THREAD

**Issue by daomeixiong2547** [leleliu008/ndk-pkg#1]
请问我可以使用这个编译libimobiledevice生成运行库so库，并在android studio中使用吗？

**Comment by leleliu008** [comment]
目前，这个软件的功能还没有完全编写完毕。但是是可以正常编译的，只是你需要把编译好的SO和它的依赖SO文件自己复制到你的android工程里

**Comment by daomeixiong2547** [comment]
> 目前，这个软件的功能还没有完全编写完毕。但是是可以正常编译的，只是你需要把编译好的SO和它的依赖SO文件自己复制到你的android工程里

了解，谢谢，目前正在尝试中，中间会遇到网络问题，我准备windows上装一个cygwin尝试

**Comment by leleliu008** [comment]
虽然支持运行在msys2和cygwin中，但是没有经过CI测试，可能会遇到编译失败的情况，如果你用的是Windows系统，最好用WSL或者Docker运行在GNU/Linux环境下。当然，愿意折腾的话，可以尝试运行在msys2或cygwin中。

**Comment by daomeixiong2547** [comment]
> 虽然支持运行在msys2和cygwin中，但是没有经过CI测试，可能会遇到编译失败的情况，如果你用的是Windows系统，最好用WSL或者Docker运行在GNU/Linux环境下。当然，愿意折腾的话，可以尝试运行在msys2或cygwin中。

好的，那我装个ubuntu尝试一下！
