### ISSUE TITLE
How to install only one abis

### ISSUE THREAD

**Issue by DLTech21** [leleliu008/ndk-pkg#10]
how to use TARGET_OS_ABI??

**Comment by leleliu008** [comment]
ndk-pkg install four abis except modify the source file.

https://github.com/leleliu008/ndk-pkg/blob/master/bin/ndk-pkg#L4816

I wonder why do you wanna install only one abi.

**Comment by DLTech21** [comment]
debug one arch sometimes

**Comment by leleliu008** [comment]
install only one abis every time. this feature had been implmented in new release which was published just now. You can try it.
