### ISSUE TITLE
这仓库上个别文件为什么始终显示找不到，其他的都能找到

### ISSUE THREAD

**Issue by pickupsb** [leleliu008/ndk-pkg#11]
libarchive  arm64-v8a的libbz2.so始终找不到，而且是没有soname的，能看看是怎么回事吗，困扰好久了，多谢了

**Comment by leleliu008** [comment]
你能说仔细点儿吗？我没看明白你在说啥

**Comment by leleliu008** [comment]
发布了新版本，解决了一些bug，可以尝试新版本看看能不能解决。
