### ISSUE TITLE
编译静态库

### ISSUE THREAD

**Issue by DLTech21** [leleliu008/ndk-pkg#13]
目前静态库的编译方式不太清楚，能否增加参数解决？

**Comment by leleliu008** [comment]
你的意思是只编译静态库，不编译动态库吗？

**Comment by DLTech21** [comment]
对的

**Comment by leleliu008** [comment]
```
ndk-pkg install openssl --install-lib=both | no | shared | static | yes
```
这个接口是预留出来了，但是没有完全实现，如果你有好的想法，欢迎留言

**Comment by DLTech21** [comment]
有时候需要编译静态库为了是其他项目写jni去引用

**Comment by DLTech21** [comment]
> ```
> ndk-pkg install openssl --install-lib=both | no | shared | static | yes
> ```
> 
> 这个接口是预留出来了，但是没有完全实现，如果你有好的想法，欢迎留言

这个很好啊，啥时候更新？另外看看xcpkg的issue，同样也是静态库问题

**Comment by leleliu008** [comment]
你在`jni`里使用的话，最好include我写好的`ndk-pkg.cmake`

**Comment by DLTech21** [comment]
我是其他c项目引用，然后通过ndk-build再打包so的

**Comment by leleliu008** [comment]
因为库太多，很多库没法统一处理，需要一一适配，我本人也没有那么多时间去弄，你也看到了，只是我自己一个人写，这个需要大量时间

**Comment by leleliu008** [comment]
还在用ndk-build？为啥不用cmake？

**Comment by leleliu008** [comment]
欢迎提出意见和建议

**Comment by leleliu008** [comment]
如果你只是想使用静态库，其实静态库和动态库都生成也没有关系的，但是这个确实需要写一点儿代码做处理，我已经在想办法解决这个问题，想到了一些办法，但是都觉得不完美，因此还在思考中。。。

**Comment by DLTech21** [comment]
加个好友探讨？？

**Comment by leleliu008** [comment]
把你的微信号发到我的邮箱，我加你

**Comment by DLTech21** [comment]
已经发gmail

**Comment by leleliu008** [comment]
已加
