### ISSUE TITLE
Attempting to install on Android using Termux

### ISSUE THREAD

**Issue by greenbadge** [leleliu008/ndk-pkg#14]
I have been trying to install packages on my android device using termux, but each package fails on step 3 because an android NDK cannot be found and one will not install.  Is there a solution to this?

**Comment by leleliu008** [comment]
sorry, I made a mistake, you can modify the soucecode directly, run `vi ~/../usr/bin/ndk-pkg`, change `if ndkmanager install r23b` to `if ndkmanager install r23a`, as an immediate workaround. I will fix this problem tomorrow.

**Comment by leleliu008** [comment]
this problem has been fixed, run following comands in your terminal to update fixes:

```
ndk-pkg upgrade @self
ndk-pkg update
```
