### ISSUE TITLE
编译libssh2 的arm64-v8a版本报 crypt ssl z 不存在（其实是存在的），但是armv7 版本不报错

### ISSUE THREAD

**Issue by lhg-turingvideo** [leleliu008/ndk-pkg#15]

**Comment by leleliu008** [comment]
发一下详细的错误日志、你用的ndk-pkg的版本，你用的ndk-pkg的完整命令，ndk-pkg仓库是否是最新的？ndk的版本号。我在GitHub Actions上有测试，没有出现编译问题

你执行
```
ndk-pkg --version
ndk-pkg install libssh2 |& tee log.txt
```

**Comment by lhg-turingvideo** [comment]
NDK 版本21.4.7075529
![54545](https://user-images.githubusercontent.com/83744676/162561218-269d8ce0-8030-4ccd-9c68-887b998ecc19.png)
另外我看编译成的so是 so.1.1 文件名和SONAME ？
这样在android中是无法引用的

**Comment by lhg-turingvideo** [comment]
ndk-pkg 版本 0.1.31

**Comment by leleliu008** [comment]
您有什么特殊需求吗？ndk r23以下的版本已经被淘汰了。没有特殊需要，您应该使用r23

**Comment by leleliu008** [comment]
你如果使用我内置的NDK（23.1.7779620）应该不会有问题。

unset ANDROID_NDK_HOME
unset ANDROID_NDK_ROOT

这样就不会使用你 ANDROID_NDK_HOME和ANDROID_NDK_ROOT指向的NDK了，ndk-pkg会自动下载合适的NDK版本

**Comment by leleliu008** [comment]
https://developer.android.com/ndk/downloads
https://github.com/android/ndk/wiki/Unsupported-Downloads

**Comment by leleliu008** [comment]
关于soname带有版本号的问题，我这几天会重新发布一个版本解决这个问题。你如果想现在就使用这个功能，也是可以的，只是我把这个功能注释掉了，因为soname带有版本号不是Android不支持，确切的说是Android的APK不支持，Android系统是支持的，如果你使用命令行或者Termux的话。这也就是我把这功能注释掉的原因。

**Comment by leleliu008** [comment]
![Screenshot from 2022-04-09 15-27-53](https://user-images.githubusercontent.com/3040852/162561743-e6ffe163-0c37-4be0-b8a4-1c6f0192c576.png)

你直接修改源码，把这段注释的注释符号去掉，就会去掉soname的版本号

不然等几天我重新发布一个新版，就好了

**Comment by lhg-turingvideo** [comment]
多谢明白了

**Comment by lhg-turingvideo** [comment]
![image](https://user-images.githubusercontent.com/83744676/162598419-a124c571-768b-470a-ac81-203055dd5de1.png)
大神请教下，编译的libgit2使用到libssl 报这个错

**Comment by leleliu008** [comment]
不好意思，回复的晚了，这是因为默认是release mode，在release mode下把所有的symbol全部remove掉了，忘记加上-S参数了，这个bug过两天重新发布之后会解决掉，你现在需要做的是：
```bash
rm -rf ~/.ndk-pkg/install.d
ndk-pkg install libgit2 --build-type=debug
```
这个意思是把你原来构建的所有包全部删除掉，然后重新编译，但是必须是debug mode。因为debug mode下不会删除symbol

**Comment by leleliu008** [comment]
感谢你报告的bug，我发布了新版会告诉你，你先用我上面给出的解决办法，大约还要等3天左右才能发布新版本

**Comment by leleliu008** [comment]
@lhg-turingvideo 

最新版本刚刚已经发布。已解决此问题。
更新ndk-pkg自身：`ndk-pkg upgrade @self`
更新ndk-pkg仓库：`ndk-pkg update`

**Comment by leleliu008** [comment]
我先关闭该issue了，如果有问题，可以重新打开

**Comment by lhg-turingvideo** [comment]
好的 多谢

**Comment by leleliu008** [comment]
@lhg-turingvideo 上一个版本有bug，因为重构了一下，改出了问题，重新发布了一个版本。
