### ISSUE TITLE
How to generate debug symbols for release builds?

### ISSUE THREAD

**Issue by unhonin** [leleliu008/ndk-pkg#19]
Hi,

Thank you so much for the wonderful project, everything works really fine on my case. I was wondering if there is any input arguments that enables the debug symbols generating? For interpreting the crashing stack traces?

Thank you

**Comment by leleliu008** [comment]
```
ndk-pkg install <PKG-NAME> --build-type=debug
```

**Comment by unhonin** [comment]
Thank you so much
