### ISSUE TITLE
Accelerate builds with make -j<num_cores>, ccache and quiet stdout.

### ISSUE THREAD

**Issue by ghost** [leleliu008/ndk-pkg#2]
## Making use of make multi-processing -j switch/project specific JOBS=:

As it stands right now the builds are conducted with a single core/thread, which takes a lot of time.

### General implementation help:
``$(nproc --all)`` can be used on linux/unix-like platforms to find out the number of cores(threads) the system has;

### Advantages:
* Close to linear time, compile time gains per thread/core.

### Disadvantages:
* Increased ram and cpu usage.
* Not sure if ones you have, but some libraries are very heavy and can take up couple gigabytes of ram when being linked/compiled with multiple jobs.
* Decreased log readability(because things are compiled in a non linear fashion, make jobs can partially continue despite one of components failing)
[That isn't to say that you will get an echo of an ongoing compilation and stderr printed out in an unreadable way. But a lot of users are used to this, make will still return an appropriate exit code].

### Pitfalls:
* Some libraries/binaries will fail to compile when using multiple make jobs.
for example if headers are generated at runtime on a makefile this can make a multi job/multi processed make fail due to unregenerated header. 
* Some libraries/programs go around it, by having a JOBS/jobs variable within them:
make jobs=<number of cores/threads> / make JOBS=<number of cores/threads> instead of make -j<number of cores/threads> , this way they complete some part of the job in a linear fashion, and then complete the rest of the cycle with multi-processing.

### Time gains:
* Depending on cpu and what user does in the background during the build, substantial compile time gains, close to (single core time*1/threads) when user leaves the computer be to compile.

### General implementation help:
ccache invocation:
* ``ccache --config-path <configuration> <compiler/compiler_path> <compilation options>``
* The configuration file allows setting the size the cache will grow to.
* The cache can be cleared with -C switch

### Advantages:
* Substantially decreases subsequent compilation time of building C files, and decreases time of building new versions of libraries.
* Substantially increases speed of incremental builds (library updates).

### Disadvantages:
* Cache of ccache might be no longer valid when ndk updates or sysroot changes.
* Can take a lot of space, user needs to be able to set.
* ccache is essentially a wrapper for a C/C++ compiler, it creates a sort of database with hashes and resolves hash collisions, naturally this means it has some sort of overhead and user gets increased compile times on cache misses.
* I would personally make it an optional flag.

### Pitfalls:
* Some projects might not accept ccache easily or recognize the compiler and apply gcc specific compiler flags to clang and vice versa.
* I am not sure what happens when cache fills up, and whether it will remove files which don't get any/a lot of cache hits.

### Time gains:
* First time +1-5% compile time
* -99% on cache hits.
* Linking time might not be accelerated much.

### Advantages:
* Easy to implement, just move stdout/stderr to /dev/null

### Disadvantages:
* Makes reading build logs factually impossible.
* By no means should it be the default option.
* Unknown if there are any time improvements.

### Time gains:
* Unknown, it is often recommended for improved boot times to "quiet" the output when using the SSDs.
* It might be worth adding as a switch, but I suspect time gained might not be substantial.

**Comment by ghost** [comment]
Hmm maybe I missed something, I see you have
https://github.com/leleliu008/ndk-pkg/blob/master/bin/ndk-pkg#L188
```bash
nproc() {
    if command nproc --version > /dev/null 2>&1 ; then
        command nproc
    elif test -f /proc/cpuinfo ; then
        grep -c processor /proc/cpuinfo
    elif command -v sysctl > /dev/null ; then
        sysctl -n machdep.cpu.thread_count
    else
        echo 4
    fi
}
```
However during the build I noticed that my cpu usage enduced due to ndk-pkg was 18%, which at 6 cores and 6 threads equals to 1.1 cores used out of 6 at best(16% is 1 core).

And the builds were very linear let me see what's up with that.

I see this change is inflight!

**Comment by kubast2** [comment]
While md5sum is faster than sha256sum, even though xxhash isn't as well known it is magnitudes faster than md5sum.
Both however shouldn't be used for cryptographic purposes.

**Comment by ghost** [comment]
This patch adds a $NPROC environmental variable, evaluated at init by calling the $(nproc) function and saving the result to a variable;

$MULTI_PROCESS variable needs to be evaluated per package, the default option should be true, unless a package is marked;

$JOBS_VAR variable needs to be evaluated per package, the default option should be false, unless a package is marked;

It only implements multi-processed builds with make;

**Comment by ghost** [comment]
#5

**Comment by leleliu008** [comment]
all features have been implemented in new release. 

run `ndk-pkg upgrade @self` to upgrade self
run `ndk-pkg update` to update repos.
