### ISSUE TITLE
configure: error: Namespace support is required to build ICU.

### ISSUE THREAD

**Issue by wwLin-slam** [leleliu008/ndk-pkg#20]
```
checking for namespace support... no
configure: error: Namespace support is required to build ICU.
/root/.ndk-pkg/installing.d/android/21/icu4c/src/source/runConfigureICU: ./configure failed
💔  package [icu4c] install failed! you can go to directory[/root/.ndk-pkg/installing.d/android/21/icu4c] to look at the details.
```

**Comment by wwLin-slam** [comment]
作者您好！在使用docker exec -it ndk-pkg ndk-pkg install boost 安装时出现以上问题，麻烦您帮忙看看。谢谢！

**Comment by leleliu008** [comment]
请先执行下面的命令：

```
docker exec -it ndk-pkg apt install -y g++ zlib1g-dev
docker exec -it ndk-pkg ndk-pkg install boost
```

因为我忘记在容器内安装C++编译器了。

**Comment by wwLin-slam** [comment]
> 请先执行下面的命令：
> 
> ```
> docker exec -it ndk-pkg apt install -y g++ zlib1g-dev
> docker exec -it ndk-pkg ndk-pkg install boost
> ```
> 
> 因为我忘记在容器内安装C++编译器了。

**Comment by wwLin-slam** [comment]
> 请先执行下面的命令：
> 
> ```
> docker exec -it ndk-pkg apt install -y g++ zlib1g-dev
> docker exec -it ndk-pkg ndk-pkg install boost
> ```
> 
> 因为我忘记在容器内安装C++编译器了。

感谢作者的帮助！

**Comment by leleliu008** [comment]
也感谢你的报告！

这个容器的确在GitHub Actions上没有完整测试过，我会尽快更新一个新版本，把此容器做个完整的测试。

**Comment by leleliu008** [comment]
最新版本已发布，容器也经过了测试。
