### ISSUE TITLE
Need Some Help with building boost

### ISSUE THREAD

**Issue by amreisa** [leleliu008/ndk-pkg#22]
I trying building boost with NDK But I got errors.

My command `./ndk-pkg install boost --ndk-home=/home/amr/Android/Sdk/ndk/20.1.5948944/ ` I use Linux.

I got this error message `=>> STEP 42 : adjust ELF files for android-21/arm64-v8a/libiconv 
💔  invalid ELF file: /home/amr/.ndk-pkg/installed/android-21/arm64-v8a/libiconv/bin/iconv. Android 5.0 and later requires dynamically linked executable to support PIE (position-independent executables).
💔  package installation failure: android-21/arm64-v8a/libiconv`

Thanks for all good work.

Amr

**Comment by leleliu008** [comment]
Could you attach the whole log?

**Comment by leleliu008** [comment]
It's best to use this software via docker if you known the docker. I have test the docker.

**Comment by amreisa** [comment]
Can you recommend me the names of the images and programs needed under docker ?
I will upload log file after I finish it.

**Comment by leleliu008** [comment]
Please read this: https://github.com/leleliu008/ndk-pkg#install-ndk-pkg-via-docker

**Comment by amreisa** [comment]
My Log file [log.txt](https://github.com/leleliu008/ndk-pkg/files/11933010/log.txt)

**Comment by leleliu008** [comment]
I can't reproduce this. 

my reproduce steps:

**step1. create a docker container**

```bash
podman create -it --name manjaro manjarolinux/base
podman start manjaro
podman exec -it manjaro bash
```

**step2. run commands in the docker container**

```bash
pacman -Syyuu --noconfirm
pacman -S     --noconfirm gcc

curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
chmod a+x ndk-pkg
./ndk-pkg setup
./ndk-pkg update
./ndk-pkg install boost
```

I guess your ndk version is too old. just run `./ndk-pkg install boost` will do the trick, ndk-pkg will install a approprivate version of ndk for you when `--ndk-home=` argument is unspecified.

**Comment by leleliu008** [comment]
oh, I see, your ndk version is `20.1.5948944`, it's too old. the older ndk do not compile PIE executable. That's what the error logs tell you.
