### ISSUE TITLE
Installing gnutls

### ISSUE THREAD

**Issue by armanTabib** [leleliu008/ndk-pkg#23]
Hello, 
I'm trying to install gnutls. So i run this command: 
`./ndk-pkg install gnutls --ndk-home=/some/path/to/ndk/android-ndk-r25c`
and I get error :
```
=>> STEP 2 : load formula 
supported min sdk api level: 24
requested min sdk api level: 21
💔  package installation failure: 'android-21/arm64-v8a/gnutls'
    supported min sdk api level: 24
    requested min sdk api level: 21
💔  package installation failure: android-21/arm64-v8a/gnutls

```
and when I try to install it with this command: 
`./ndk-pkg install gnutls --ndk-home=/some/path/to/ndk/android-ndk-r25c --api=24`
I get error : 
`💔  unrecognized option: --api=android-24`
P.S.: My os is ubuntu 23.04

**Comment by leleliu008** [comment]
```bash
./ndk-pkg install android-24/arm64-v8a/gnutls
./ndk-pkg install android-24/armeabi-v7a/gnutls
```
