### ISSUE TITLE
Don't use a 5000 line Shell Script

### ISSUE THREAD

**Issue by llothar** [leleliu008/ndk-pkg#25]
I like the idea of this project but i gave up after seeing that it is a giant shell script.
The fixable mistakes are:

-  Rewrite it in a good script language, i would prefer ruby.
   One day when it gets widely used you will need a real programming language for better error handling.
   
-  Break it down into readable files. 

You will never get a supporting group until you change this because i wouldn't trust a minute of using it. 
Spend time to read the readme and writing this already.

**Comment by leleliu008** [comment]
Thanks for your comments and advises.

I just use shell script to implement my ideas quickly.

I will rewrite it in C at some point.
