### ISSUE TITLE
-j | --jobs no longer work like before

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ndk-pkg#27]
Hello,
I noticed that in the recent version (since the last 2 weeks), I can no longer use these:
```bash
-j="$(($(nproc)+1))"
--jobs="$(($(nproc)+1))"
```

Previously they used to work, now only this works:
```bash
-j "$(($(nproc)+1))"
```

Was this an unintentional regression or a deliberate choice to have only one way to specify max number of jobs?

**Comment by leleliu008** [comment]
only `-j <N>` is supported now. I changed a lot, you can read the help.

**Comment by Azathothas** [comment]
Oh, I see
Thanks!

**Comment by Azathothas** [comment]
A lot of things broke...
the old `--fsle` option got changed to `--static` and other things.

And the versioned releases contain no changelog to denote breaking changes...

**Comment by leleliu008** [comment]
This software is being actively developed. It's in beta stage and may not be stable. Some features are subject to change without notice.

using `ndk-pkg --help` to see the usage.

I do not want to write the change logs at this stage.

I do not want to consider backward compatibility at this stage.

I will do these things when this tool's version reach 1.x

**Comment by leleliu008** [comment]
> the old `--fsle` option got changed to `--static` and other things.

`--fsle` looks strange, `--static` is used by `gcc` and `clang`, although it was not documented.

I will add a new option `--static-pie` to support `static-pie`
