### ISSUE TITLE
install libimobiledevice failure on  Mac

### ISSUE THREAD

**Issue by coderjing** [leleliu008/ndk-pkg#28]
step：
ndk-pkg update
ndk-pkg install libimobiledevice

✅️ android-21-arm64-v8a/libplist was successfully installed.

Installation android-21-arm64-v8a/libimobiledevice-glue start
=>> STEP 1 : load formula
💔 ndk-pkg: package installation failure: 'android-21-arm64-v8a/libimobiledevice-glue'
supported min sdk api level: 24
requested min sdk api level: 21
💔 ndk-pkg: package installation failure: android-21-arm64-v8a/libimobiledevice-glue

libimobiledevice.yml: api-min: 24

**Comment by leleliu008** [comment]
```
ndk-pkg install android-24-arm64-v8a/libimobiledevice
```

**Comment by coderjing** [comment]
谢谢大佬，我试试，感谢感谢，回复神速！

**Comment by leleliu008** [comment]
你可以使用GitHub Actions来编译，不用在你的本地机器上编译 https://github.com/leleliu008/ndk-pkg-package-manually-build

**Comment by coderjing** [comment]
好的，谢谢大佬，ndk-pkg install android-24-arm64-v8a/libimobiledevice  编译成功了，非常感谢！再问一下，如果我修改了libimobiledevice某个组件的源码，您的ndk-pkg怎么编译呢，貌似libimobiledevice需要root权限运行

**Comment by leleliu008** [comment]
> 如果我修改了libimobiledevice某个组件的源码

这是啥意思？libimobiledevice的组件是舍意思？

**Comment by coderjing** [comment]
嗷，我是iOS开发，习惯了，就是libimobiledevice库里面的libusbmuxd，他依赖libusb，libusb在Android平台应该要root，要么就要改源码

**Comment by leleliu008** [comment]
比如，你要修改libusb的源码，修改完之后要重新编译，对吧？

这种情况就是，你需要修改libusb对应的formula文件，文件路径为`~/.ndk-pkg/repos.d/official-core/formula/libusb.yml`

将 src-url 字段修改为 `src-url: dir:///Users/coderjing/libusb` , `/Users/coderjing/libusb`就是你修改后的源码的路径

然后执行 

```
ndk-pkg uninstall android-24-arm64-v8a/libusb
ndk-pkg install android-24-arm64-v8a/libusb
```

**Comment by coderjing** [comment]
非常详细了，有心了，太感谢大佬了！！
