### ISSUE TITLE
how to build also static libraries?

### ISSUE THREAD

**Issue by juha-h** [leleliu008/ndk-pkg#6]
When I run `ndk-pkg install abseil` only dynamic (.so)  libraries are build.  How can I get also static (.a) libraries built?

**Comment by leleliu008** [comment]
step1. edit the formula of  `abseil` package
```bash
ndk-pkg formula edit abseil
```
step2. add the following code
```cmake
-DBUILD_SHARED_LIBS=OFF
```
step3. rebuild it
```bash
ndk-build install abseil
```

**Comment by juha-h** [comment]
Thanks.
