### ISSUE TITLE
ndk-pkg install gnutls  failed?

### ISSUE THREAD

**Issue by TapuA** [leleliu008/ndk-pkg#7]
I follow this guide to install gnutls, but fail when install nettle.  I can't solve

http://blog.fpliu.com/project/ndk-pkg/package?name=gnutls

Ubuntu 20.04    
NDK android-ndk-r21e

errors:

=>> STEP 9 : build for native 
🔥  no build0  function defined in formula, skipped.

=>> STEP 12 : calculate dependencies 
🔥  graphviz is not installed. we do not generate png format dependency image.
┌────────┐
│ nettle │
└────────┘
  │
  │
  ▼
┌────────┐
│  gmp   │
└────────┘

[✘] install nettle/armeabi-v7a failed! you can go to /tmp/tmp.w4KPQ6KaXM to see see.

**Comment by TapuA** [comment]
end with

configure: exit 1

**Comment by leleliu008** [comment]
step1. upgrade the ndk-pkg to the latest version
```
ndk-pkg upgrade-self   ＃for older version
ndk-pkg upgrade ＠self  #for newer version
```
step2. update the formula-repository to the latest version
```
ndk-pkg update
```
step3. install packages what you want
```
ndk-pkg install gnutls
```
when facing problems, try above steps first.

**Comment by leleliu008** [comment]
`gnutls` is built successfully on `ubuntu-20.04` in my [Github Actions CI](https://github.com/leleliu008/ndk-pkg-formula-repository/runs/3778739959?check_suite_focus=true)

if you still facing problems after trying above steps, please attach full install logs here, the install logs location is `~/.ndk-pkg/cache.d/log.d/$PACKAGE`

**Comment by TapuA** [comment]
upgrade-self failed.  Can access to github.com, but can not access to upgrade url


root@ub:/home/liuhao# ndk-pkg upgrade-self
==> mktemp -d
==> cd /tmp/tmp.tkUzhhe775
==> curl --fail --retry 20 --retry-delay 30 --location -o /tmp/tmp.tkUzhhe775/self 'https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443

**Comment by leleliu008** [comment]
Do you in China at the moment? If yes, please try running `ndk-pkg upgrade-self --china`, `--china` argument will force ndk-pkg using GitHub's Chinese mirror.

**Comment by TapuA** [comment]
Yes. It works with -china, thank you very much.

**Comment by TapuA** [comment]
upgrade-self works.  install nettle gnutls still fail.      I email log to you because of attach log here also fail.

**Comment by TapuA** [comment]
configure:3976: checking if LD -Wl,--version-script works
configure:3994: armv7a-linux-androideabi27-clang -o conftest --sysroot /home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Qunused-arguments -Os -fpic -I/root/.ndk-pkg/install.d/gmp/armeabi-v7a/include --sysroot /home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Qunused-arguments -I/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arm-linux-androideabi -include /root/.ndk-pkg/include.h -I/root/.ndk-pkg/install.d/gmp/armeabi-v7a/include -L/root/.ndk-pkg/install.d/gmp/armeabi-v7a/lib --sysroot /home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -L/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/27 -L/root/.ndk-pkg/install.d/gmp/armeabi-v7a/lib -Wl,--version-script=conftest.map conftest.c  >&5
/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: conftest.map:2:1: syntax error, unexpected $end, expecting '{'
/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: unable to parse version script file conftest.map
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3994: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "nettle"
| #define PACKAGE_TARNAME "nettle"
| #define PACKAGE_VERSION "3.6"
| #define PACKAGE_STRING "nettle 3.6"
| #define PACKAGE_BUGREPORT "nettle-bugs@lists.lysator.liu.se"
| #define PACKAGE_URL ""
| #define HAVE_LINK_IFUNC 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }

**Comment by TapuA** [comment]
[install_nettle_fail.txt](https://github.com/leleliu008/ndk-pkg/files/7273049/install_nettle_fail.txt)

attach files successfully when open v2ray...

**Comment by leleliu008** [comment]
```
configure: error: Cannot find 'makeinfo', required for documentation.
```
You must install `makeinfo` command on your build machine.

`makeinfo` command is ususally part of the `texinfo` package in your distribution.

try following instruction to install :

```
sudo apt -y install texinfo
```

**Comment by TapuA** [comment]
thank you !!!
