### ISSUE TITLE
single abseil static library

### ISSUE THREAD

**Issue by juha-h** [leleliu008/ndk-pkg#8]
`ndk-pkg abseil` produces large number of static libraries (*.a files).  Is there some way to produce a single combined library, e.g. `libabsl.a`?

**Comment by leleliu008** [comment]
I use Cmake to build the abseil, there is no option to merge all static libraries into one, and i have no plan to do this thing too.

rerference:
- https://github.com/abseil/abseil-cpp/issues/367- 
- https://www.wikitechy.com/tutorials/linux/how-to-merge-two-ar-static-libraries-into-one

**Comment by juha-h** [comment]
OK, thanks.
