### ISSUE TITLE
install glib failed 

### ISSUE THREAD

**Issue by TapuA** [leleliu008/ndk-pkg#9]
[✔] gettext have been installed successfully.
=============== Installing glib ===============

=>> STEP 1 : load formula 

=>> STEP 2 : handle required commands 
    Found 1 package manager : apt
🔥  meson command is required, but it is not found, I will install it via apt
==> apt -y install meson

**---- meson is installed already**
[install.log.txt](https://github.com/leleliu008/ndk-pkg/files/7277010/install.log.txt)
[meson-log.txt](https://github.com/leleliu008/ndk-pkg/files/7277011/meson-log.txt)

==> install -d /tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a
==> cd /tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a
==> /usr/bin/meson setup --prefix=/root/.ndk-pkg/install.d/glib/armeabi-v7a --buildtype=release --backend=ninja --pkg-config-path=/root/.ndk-pkg/install.d/zlib/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/bzip2/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/pcre/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/libffi/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/libiconv/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/ncurses/armeabi-v7a/lib/pkgconfig:/root/.ndk-pkg/install.d/gettext/armeabi-v7a/lib/pkgconfig --build.pkg-config-path= --cross-file=/tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a/cross-file -Dnls=disabled -Dman=false -Dgtk_doc=false -Diconv=external -Ddtrace=false -Dinternal_pcre=false -Dinstalled_tests=false -Dbsymbolic_functions=false /tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a /tmp/tmp.yXR5km2Bwm
The Meson build system
Version: 0.53.2
Source dir: /tmp/tmp.yXR5km2Bwm
Build dir: /tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a
Build type: cross build
Project name: glib
Project version: 2.66.0
Appending CFLAGS from environment: '--sysroot /home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Qunused-arguments -Os -fpic'
Appending LDFLAGS from environment: ['-L/root/.ndk-pkg/install.d/gettext/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/ncurses/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/libiconv/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/libffi/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/pcre/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/bzip2/armeabi-v7a/lib', '-L/root/.ndk-pkg/install.d/zlib/armeabi-v7a/lib', '--sysroot', '/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot', '-L/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/27', '-lpcre', '-liconv', '-lm', '-lz']
Appending CPPFLAGS from environment: '-I/root/.ndk-pkg/install.d/gettext/armeabi-v7a/include -I/root/.ndk-pkg/install.d/ncurses/armeabi-v7a/include -I/root/.ndk-pkg/install.d/libiconv/armeabi-v7a/include -I/root/.ndk-pkg/install.d/libffi/armeabi-v7a/include -I/root/.ndk-pkg/install.d/pcre/armeabi-v7a/include -I/root/.ndk-pkg/install.d/bzip2/armeabi-v7a/include -I/root/.ndk-pkg/install.d/zlib/armeabi-v7a/include --sysroot /home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Qunused-arguments -I/home/liuhao/Desktop/tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arm-linux-androideabi -include /root/.ndk-pkg/include.h'

meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 8] Exec format error: '/tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a/meson-private/sanitycheckc.exe'.

A full log can be found at /tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a/meson-logs/meson-log.txt
[✘] install glib/armeabi-v7a failed! you can go to /tmp/tmp.yXR5km2Bwm to see see.

**Comment by TapuA** [comment]
/tmp/tmp.yXR5km2Bwm/1633338570/armeabi-v7a/meson-private/sanitycheckc.exe

**Comment by leleliu008** [comment]
It seems that it's a bug of meson. I recommend you to install Homebrew on your Ubuntu build machine, and remove the meson package installed by apt. because the packages in apt repo's are usually too old. if HomeBrew is installed, ndk-pkg will install softwares from Homebrew. Softwares in HomeBrew all are the latest version.

[HomeBrew homepage](https://brew.sh/)

**Comment by TapuA** [comment]
install HomeBrew failed because Ubuntu in VirtualBox can not access v2ray in PC.

But I install glib successfully after update meson through " pip3 install meson ".

thank you very much!!!
